/**
 * Bug-bounty report builder. Takes a verified finding (with proof) and produces
 * a Markdown report and a structured object suitable for HackerOne / Bugcrowd
 * submission. NEVER fabricates evidence — only structures what was verified.
 */

const SEV_RATING = {
  critical: { label: 'Critical', cvssBand: '9.0–10.0', priority: 'P1' },
  high:     { label: 'High',     cvssBand: '7.0–8.9',  priority: 'P2' },
  medium:   { label: 'Medium',   cvssBand: '4.0–6.9',  priority: 'P3' },
  low:      { label: 'Low',      cvssBand: '0.1–3.9',  priority: 'P4' },
  info:     { label: 'Informational', cvssBand: 'N/A', priority: 'P5' },
};

function buildReport(finding, target) {
  const sev = SEV_RATING[finding.severity] || SEV_RATING.low;
  const title = `[${sev.label}] ${finding.title}${finding.where && finding.where !== target ? ` on ${shortHost(finding.where)}` : ''}`;

  const summary = finding.impact;
  const steps = buildSteps(finding);
  const impact = expandImpact(finding);
  const remediation = finding.remediation || 'Apply current security best-practice for this class of finding.';
  const proofBlock = formatProof(finding);

  const markdown = `# ${title}

**Target:** ${target}
**Affected asset:** ${finding.where || target}
**Severity:** ${sev.label} (${sev.priority}, CVSS ${sev.cvssBand})
**Validated at:** ${finding.validatedAt}

## Summary

${summary}

## Steps to Reproduce

${steps}

## Proof of Concept

${proofBlock}

## Impact

${impact}

## Recommended Fix

${remediation}

---
_Report generated by CyberMindSpace · evidence captured live, not inferred._
`;

  return {
    title,
    severity: sev.label,
    priority: sev.priority,
    cvssBand: sev.cvssBand,
    target,
    asset: finding.where || target,
    summary,
    steps,
    impact,
    remediation,
    proof: finding.proof,
    markdown,
    finding,
  };
}

function shortHost(input) {
  try { return new URL(input).host; } catch (_) { return input; }
}

function buildSteps(finding) {
  const steps = [];
  switch (true) {
    case finding.kind === 'cors':
      steps.push('1. Send a `GET` request to the target with an attacker-controlled `Origin` header.');
      steps.push('2. Inspect the response for `Access-Control-Allow-Origin` and `Access-Control-Allow-Credentials`.');
      steps.push('3. Confirm the server reflects the attacker origin (and, if Critical, also returns `Access-Control-Allow-Credentials: true`).');
      steps.push('');
      steps.push('```bash');
      steps.push(`curl -sI '${finding.where}' \\`);
      steps.push(`  -H 'Origin: https://attacker.example' \\`);
      steps.push(`  | grep -i 'access-control'`);
      steps.push('```');
      break;

    case /^exposure:/.test(finding.kind):
      steps.push(`1. Send an unauthenticated \`GET\` request to \`${finding.where}\`.`);
      steps.push('2. Verify the response status is `200 OK` and the body matches the resource fingerprint shown in the proof.');
      if (finding.proof?.secrets?.length) steps.push('3. Verify the response contains live secret-shaped values (sample shown redacted in proof).');
      steps.push('');
      steps.push('```bash');
      steps.push(`curl -i '${finding.where}'`);
      steps.push('```');
      break;

    case finding.kind === 'endpoint-secret-leak':
      steps.push(`1. Open \`${finding.where}\` (or replay it via the Wayback Machine).`);
      steps.push('2. Search the response body for the secret patterns listed in the proof.');
      steps.push('3. Confirm at least one matching value is still functional against the issuing service.');
      break;

    case finding.kind === 'subdomain-takeover':
      steps.push(`1. Resolve the CNAME for \`${finding.where}\`.`);
      steps.push('2. Visit the subdomain over HTTP and confirm the provider\'s "unclaimed" fingerprint in the response body.');
      steps.push('3. (Do not actually claim it on a live target — proof of concept stops here.)');
      steps.push('');
      steps.push('```bash');
      steps.push(`dig +short CNAME ${finding.where}`);
      steps.push(`curl -s 'http://${finding.where}/' | head`);
      steps.push('```');
      break;

    case finding.kind === 'open-port':
      steps.push(`1. From an external network, attempt a TCP connection to \`${finding.where}\`.`);
      steps.push('2. Observe a successful handshake and capture any service banner.');
      steps.push('');
      steps.push('```bash');
      steps.push(`nc -vz ${finding.where.replace(':', ' ')}`);
      steps.push('```');
      break;

    case /^config:/.test(finding.kind):
      steps.push(`1. Issue a \`GET\` request to ${finding.where}.`);
      steps.push('2. Inspect the response headers / cookies for the missing security directive.');
      steps.push('');
      steps.push('```bash');
      steps.push(`curl -sI '${finding.where}'`);
      steps.push('```');
      break;

    default:
      steps.push(`1. Reproduce by issuing a \`GET\` to \`${finding.where || 'the target'}\`.`);
      steps.push('2. Compare the response to the proof block below.');
  }
  return steps.join('\n');
}

function expandImpact(finding) {
  const base = finding.impact || '';
  const sev = (finding.severity || 'low').toUpperCase();
  const exploitNote = finding.exploitable
    ? '\n\n**Exploitation status:** validated end-to-end with an unauthenticated request from an external network. No credentials, exploits, or destructive payloads were used.'
    : '\n\n**Exploitation status:** the misconfiguration was observed, but a complete exploitation chain was not demonstrated. Treat this as a defense-in-depth issue unless combined with another vulnerability.';
  return `**Severity rating:** ${sev}\n\n${base}${exploitNote}`;
}

function formatProof(finding) {
  if (!finding.proof) return '_No machine-captured proof available._';
  const out = [];
  if (finding.proof.request) {
    out.push('**Request:**');
    out.push('```http');
    out.push(finding.proof.request);
    out.push('```');
    out.push('');
  }
  if (finding.proof.response) {
    out.push('**Response:**');
    out.push('```http');
    out.push(finding.proof.response);
    out.push('```');
  }
  if (finding.proof.secrets?.length) {
    out.push('');
    out.push('**Secret patterns detected (redacted):**');
    for (const s of finding.proof.secrets) {
      out.push(`- ${s.kind}: \`${s.redacted}\``);
    }
  }
  return out.join('\n');
}

module.exports = { buildReport };
