const PDFDocument = require('pdfkit');

/**
 * Generate a professional PDF report for an OSINT investigation.
 */
function generatePDF(investigation, stream) {
  const doc = new PDFDocument({ margin: 50, size: 'A4', autoFirstPage: false });
  doc.pipe(stream);

  // Colors
  const blue = '#2563EB';
  const darkBlue = '#1E3A8A';
  const gray = '#6B7280';
  const black = '#111827';
  const red = '#DC2626';

  const drawHeader = (d) => {
    d.rect(0, 0, d.page.width, 60).fill(darkBlue);
    d.fontSize(18).fill('#FFFFFF').text('CyberMindSpace', 50, 20);
    d.fontSize(8).fill('#93C5FD').text('INTELLIGENCE REPORT', 350, 25, { align: 'right', width: 200 });
  };

  const drawFooter = (d) => {
    const pageNumber = d.bufferedPageRange().count || 1;
    d.fontSize(7).fill(gray)
      .text('This report was generated by CyberMindSpace Tools. Confidential - For authorized use only.', 50, d.page.height - 40, {
        align: 'left',
        width: 300,
      });
    d.text(`Page ${d.pageNumber || ''}`, 400, d.page.height - 40, {
      align: 'right',
      width: 150
    });
  };

  // Add pages manually to trigger header/footer correctly
  doc.on('pageAdded', () => {
    drawHeader(doc);
    drawFooter(doc);
    doc.y = 80; // Start content below header
  });

  doc.addPage();

  // Target info
  doc.fontSize(14).fill(darkBlue).text('Investigation Target', 50);
  doc.moveTo(50, doc.y + 2).lineTo(550, doc.y + 2).stroke(blue);
  doc.moveDown(0.5);

  doc.fontSize(10).fill(black);
  doc.text(`Query: ${investigation.query}`);
  doc.text(`Type: ${investigation.inputType?.toUpperCase() || 'Unknown'}`);
  doc.text(`Risk Score: ${investigation.riskScore || '0'}/100`);
  doc.text(`Timestamp: ${new Date(investigation.createdAt || Date.now()).toLocaleString()}`);
  doc.moveDown(1);

  // Risk indicators
  if (investigation.riskIndicators?.length > 0) {
    checkPageBreak(doc, 50);
    doc.fontSize(12).fill(darkBlue).text('Risk Indicators');
    doc.moveTo(50, doc.y + 2).lineTo(550, doc.y + 2).stroke('#EF4444');
    doc.moveDown(0.5);
    doc.fontSize(9).fill(red);
    investigation.riskIndicators.forEach(ind => {
      checkPageBreak(doc, 20);
      doc.text(`⚠ ${ind}`, { indent: 10 });
    });
    doc.moveDown(1);
  }

  // Results sections
  const results = investigation.results || {};

  const sections = [
    { key: 'email', title: 'Email Intelligence' },
    { key: 'domain', title: 'Domain Intelligence' },
    { key: 'ip', title: 'IP Intelligence' },
    { key: 'username', title: 'Username Intelligence' },
    { key: 'port', title: 'Network Port Analysis' },
    { key: 'vuln', title: 'Vulnerability Assessment' },
    { key: 'phishing', title: 'Phishing Threat Intelligence' },
  ];

  sections.forEach(({ key, title }) => {
    const data = results[key];
    if (!data || Object.keys(data).length === 0) return;

    checkPageBreak(doc, 60);

    doc.fontSize(12).fill(darkBlue).text(title);
    doc.moveTo(50, doc.y + 2).lineTo(550, doc.y + 2).stroke(blue);
    doc.moveDown(0.5);

    doc.fontSize(9).fill(black);
    renderObject(doc, data, 0, black, gray);
    doc.moveDown(1);
  });

  doc.end();
}

function checkPageBreak(doc, neededHeight) {
  if (doc.y + neededHeight > doc.page.height - 70) {
    doc.addPage();
  }
}

function renderObject(doc, obj, depth = 0, black, gray) {
  const indent = 50 + depth * 15;
  const maxDepth = 4;

  if (depth > maxDepth) return;

  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('_')) continue;
    
    checkPageBreak(doc, 15);

    const formattedKey = formatKey(key);

    if (value && typeof value === 'object' && !Array.isArray(value)) {
      doc.fontSize(9).fill(gray).text(`${formattedKey}:`, indent);
      renderObject(doc, value, depth + 1, black, gray);
    } else if (Array.isArray(value)) {
      doc.fontSize(9).fill(gray).text(`${formattedKey}:`, indent);
      value.forEach((item, i) => {
        checkPageBreak(doc, 15);
        if (item && typeof item === 'object') {
          doc.fontSize(8).fill(gray).text(`Item #${i + 1}`, indent + 10);
          renderObject(doc, item, depth + 2, black, gray);
        } else {
          doc.fontSize(8).fill(black).text(`• ${String(item)}`, indent + 15);
        }
      });
    } else {
      const label = `${formattedKey}: `;
      const valText = String(value ?? 'N/A');
      
      // Calculate how many lines this might take
      const labelWidth = doc.widthOfString(label);
      const availableWidth = 500 - indent;
      
      doc.fontSize(9).fill(gray).text(label, indent, doc.y, { continued: true })
        .fill(black).text(valText, { width: availableWidth - labelWidth });
    }
  }
}

function formatKey(key) {
  return key.replace(/([A-Z])/g, ' $1').replace(/[._-]/g, ' ').trim().replace(/^\w/, c => c.toUpperCase());
}

module.exports = { generatePDF };
