const PDFDocument = require('pdfkit');

/**
 * Generate a professional PDF report for an OSINT investigation.
 */
function generatePDF(investigation, stream) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  doc.pipe(stream);

  // Colors
  const blue = '#2563EB';
  const darkBlue = '#1E3A8A';
  const gray = '#6B7280';
  const black = '#111827';

  // Header
  doc.rect(0, 0, doc.page.width, 100).fill(darkBlue);
  doc.fontSize(22).fill('#FFFFFF').text('CyberMindSpace', 50, 30);
  doc.fontSize(10).fill('#93C5FD').text('INTELLIGENCE REPORT', 50, 58);
  doc.fontSize(8).fill('#93C5FD').text(`Generated: ${new Date().toISOString()}`, 50, 75);

  doc.moveDown(3);

  // Target info
  doc.fontSize(14).fill(darkBlue).text('Investigation Target', 50);
  doc.moveTo(50, doc.y + 2).lineTo(550, doc.y + 2).stroke(blue);
  doc.moveDown(0.5);

  doc.fontSize(10).fill(black);
  doc.text(`Query: ${investigation.query}`);
  doc.text(`Type: ${investigation.inputType?.toUpperCase() || 'Unknown'}`);
  doc.text(`Risk Score: ${investigation.riskScore || 'N/A'}`);
  doc.text(`Date: ${investigation.createdAt || new Date().toISOString()}`);
  doc.moveDown(1);

  // Risk indicators
  if (investigation.riskIndicators?.length > 0) {
    doc.fontSize(12).fill(darkBlue).text('Risk Indicators');
    doc.moveTo(50, doc.y + 2).lineTo(550, doc.y + 2).stroke('#EF4444');
    doc.moveDown(0.5);
    doc.fontSize(9).fill('#DC2626');
    investigation.riskIndicators.forEach(ind => {
      doc.text(`⚠ ${ind}`);
    });
    doc.moveDown(1);
  }

  // Results sections
  const results = investigation.results || {};

  const sections = [
    { key: 'email', title: 'Email Intelligence' },
    { key: 'domain', title: 'Domain Intelligence' },
    { key: 'ip', title: 'IP Intelligence' },
    { key: 'username', title: 'Username Intelligence' },
    { key: 'port', title: 'Network Port Analysis' },
    { key: 'vuln', title: 'Vulnerability Assessment' },
    { key: 'phishing', title: 'Phishing Threat Intelligence' },
  ];

  sections.forEach(({ key, title }) => {
    const data = results[key];
    if (!data) return;

    // Check if we need a new page
    if (doc.y > 650) doc.addPage();

    doc.fontSize(12).fill(darkBlue).text(title);
    doc.moveTo(50, doc.y + 2).lineTo(550, doc.y + 2).stroke(blue);
    doc.moveDown(0.5);

    doc.fontSize(9).fill(black);
    renderObject(doc, data, 0, black, gray);
    doc.moveDown(1);
  });

  // Footer
  doc.fontSize(7).fill(gray)
    .text('This report was generated by CyberMindSpace Tools. Data is from public sources only.', 50, doc.page.height - 40, {
      align: 'center',
      width: doc.page.width - 100,
    });

  doc.end();
}

function renderObject(doc, obj, depth = 0, black, gray) {
  const indent = 50 + depth * 15;
  const maxDepth = 3;

  if (depth > maxDepth) return;

  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('_')) continue;
    if (doc.y > 720) doc.addPage();

    if (value && typeof value === 'object' && !Array.isArray(value)) {
      doc.fontSize(9).fill(gray).text(`${formatKey(key)}:`, indent);
      renderObject(doc, value, depth + 1, black, gray);
    } else if (Array.isArray(value)) {
      doc.fontSize(9).fill(gray).text(`${formatKey(key)}:`, indent);
      value.forEach((item, i) => {
        if (typeof item === 'object') {
          doc.fontSize(8).fill(gray).text(`  #${i + 1}:`, indent + 10);
          renderObject(doc, item, depth + 2, black, gray);
        } else {
          doc.fontSize(8).fill(black).text(`  • ${String(item)}`, indent + 10);
        }
      });
    } else {
      doc.fontSize(9).fill(gray).text(`${formatKey(key)}: `, indent, doc.y, { continued: true })
        .fill(black).text(String(value ?? 'N/A'));
    }
  }
}

function formatKey(key) {
  return key.replace(/([A-Z])/g, ' $1').replace(/[._-]/g, ' ').trim().replace(/^\w/, c => c.toUpperCase());
}

module.exports = { generatePDF };
